services:
  db:
    image: mariadb:latest
    container_name: user_db_container
    ports: 
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080