name: Admin App CI/CD

on:
  push:
    branches: [ "test/rebaseMessagetoPwa" ]

jobs:
  build:
    # runner for the job
    runs-on: ubuntu-latest 
    steps:
    # get the code
    - name: checkout
      uses: actions/checkout@v4.1.7
    # install nodejs
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 20.x

    - name: JE SUIS OU BORDEL
      run: pwd

    # install du projet  
    - name: npm install
      run: npm install
      working-directory: ./alumni/pwa-admin/
