# Définition de l'événement qui déclenche le workflow
# Ici, il est déclenché lorsqu'il y a un push sur la branche "test/rebaseMessagetoPwa"
on:
  push:
    branches: [ "test/rebaseMessagetoPwa" ]

# Définition des paramètres par défaut pour toutes les étapes du job
# Le répertoire de travail par défaut est défini ici
defaults:
  run:
    working-directory: ./alumni/pwa-admin/

# Début de la définition du job
jobs:
  build:
    # Le job sera exécuté sur une machine virtuelle Ubuntu
    runs-on: ubuntu-latest
    
    # Les étapes à exécuter dans le cadre du job
    steps:
      # Étape 1: Récupérer le code source du dépôt
      # Utilisation de l'action checkout de GitHub pour extraire le code
      - name: checkout
        uses: actions/checkout@v4.1.7

      # Étape 2: Installer Node.js sur la machine virtuelle
      # Utilisation de l'action setup-node pour spécifier la version 20.x de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          # Spécifie la version de Node.js à utiliser
          node-version: 20.x

      # Étape 3: Installation des dépendances du projet
      # Exécution de la commande `npm install` pour installer toutes les dépendances
      # nécessaires, comme défini dans le fichier `package.json` du projet
      - name: npm install
        run: npm install
