name: Intern App CI/CD

on:
  push:
    branches: [ "test/rebaseMessagetoPwa" ]

defaults:
  run:
    working-directory: ./alumni/alumni-mob/

jobs:
  build:
    # runner for the job
    runs-on: ubuntu-latest
    container: node:20.15
    steps:
    # get the code
    - name: checkout
      uses: actions/checkout@v4.1.7
    # install du projet
    - name: npm install
      run: npm install
    # setup the cache
    - name: cache setup
      uses: actions/cache@v4.0.2
      with:
        path: node_modules
        key: npmi-${{ hashFiles('package-lock.json') }}
  tu:
    needs: build # start this after the build job
    # runner for the job
    runs-on: ubuntu-latest
    container: node:20.15
    steps:
    # get the code
    - name: checkout
      uses: actions/checkout@v4.1.7
    # setup the cache
    - name: cache setup
      uses: actions/cache@v4.0.2
      with:
        path: node_modules
        key: npmi-${{ hashFiles('package-lock.json') }}
    
    - name: npm install
      run: npm install

    - run: apt-get update && apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2
    # do some tests
    - name: do test
      run: npm run test:ci
